version: 2
formats: []


python:
  version: 3.9
  install:

    - requirements: docs/requirements.txt
    - requirements: requirements.txt

    - method: pip
      path: .
      extra_requirements:
        - docs
